version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_container
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password123 
      POSTGRES_DB: terminal 
    ports:
      - "5432:5432"
    volumes:
      - terminal-data:/var/lib/postgresql/data

volumes:
  terminal-data:
